import type { Integration, Activity, TimeEntry, RiskAlert, PendingTimeEntry } from "./types";

// Today's date for demo purposes
const TODAY = new Date().toISOString().split("T")[0];

// ─── Integrations ───────────────────────────────────────────────────────────

export const MOCK_INTEGRATIONS: Integration[] = [
  {
    id: "int-1",
    source: "jira",
    displayName: "Jira",
    description: "Track tickets, sprint progress, and team velocity",
    connected: true,
    connectedAt: "2026-04-15T10:00:00Z",
    accountLabel: "axelerant.atlassian.net",
  },
  {
    id: "int-2",
    source: "github",
    displayName: "GitHub",
    description: "Monitor commits, pull requests, and code reviews",
    connected: true,
    connectedAt: "2026-04-15T10:05:00Z",
    accountLabel: "axelerant",
  },
  {
    id: "int-3",
    source: "google_calendar",
    displayName: "Google Calendar",
    description: "Capture meetings, standups, and sprint ceremonies",
    connected: true,
    connectedAt: "2026-04-15T10:10:00Z",
    accountLabel: "roshni.upadhyay@axelerant.com",
  },
  {
    id: "int-4",
    source: "slack",
    displayName: "Slack",
    description: "Track project discussions and ticket-related threads",
    connected: true,
    connectedAt: "2026-04-15T10:15:00Z",
    accountLabel: "Axelerant",
  },
  {
    id: "int-5",
    source: "mavenlink",
    displayName: "Mavenlink",
    description: "Push approved timesheets and sync project hours",
    connected: false,
  },
  {
    id: "int-6",
    source: "granola",
    displayName: "Granola",
    description: "Import AI meeting notes and action items",
    connected: false,
  },
  {
    id: "int-7",
    source: "zoom",
    displayName: "Zoom",
    description: "Auto-detect call duration and log time from meetings",
    connected: true,
    connectedAt: "2026-04-15T10:20:00Z",
    accountLabel: "roshni.upadhyay@axelerant.com",
  },
];

// ─── Activities (Real Jira data from axelerant.atlassian.net) ───────────────

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    source: "slack",
    type: "message",
    title: "Posted in #rgu-project about RGU sprint status",
    description: "Shared update on Landing Page content type progress and blockers",
    timestamp: `${TODAY}T08:30:00Z`,
    metadata: { channel: "#rgu-project", workspace: "Axelerant" },
  },
  {
    id: "act-2",
    source: "google_calendar",
    type: "meeting",
    title: "RGU Sprint Planning",
    description: "Sprint planning — reviewed backlog, prioritized Landing Page and Standard Content Page tickets",
    timestamp: `${TODAY}T09:00:00Z`,
    metadata: { calendar: "Engineering", attendees: "6" },
    durationMinutes: 45,
  },
  {
    id: "act-3",
    source: "jira",
    type: "ticket_transition",
    title: "RGU-97 moved to In Progress",
    description: "Setup Landing Page content type — transitioned from To Do to In Progress",
    timestamp: `${TODAY}T09:50:00Z`,
    metadata: { from: "To Do", to: "In Progress", assignee: "Roshni Upadhyay" },
    ticketKey: "RGU-97",
  },
  {
    id: "act-4",
    source: "github",
    type: "commit",
    title: "Add Landing Page content type config",
    description: "Created content type YAML config with fields: hero, body sections, CTA blocks",
    timestamp: `${TODAY}T10:15:00Z`,
    metadata: { repo: "axelerant/rgu-drupal", branch: "feature/RGU-97-landing-page", sha: "e4a7b12" },
    ticketKey: "RGU-97",
  },
  {
    id: "act-5",
    source: "github",
    type: "commit",
    title: "Add paragraph types for Landing Page sections",
    description: "Built hero_banner, content_section, and cta_block paragraph types",
    timestamp: `${TODAY}T11:05:00Z`,
    metadata: { repo: "axelerant/rgu-drupal", branch: "feature/RGU-97-landing-page", sha: "f8c3d45" },
    ticketKey: "RGU-97",
  },
  {
    id: "act-6",
    source: "slack",
    type: "message",
    title: "Discussion in #rgu-project about migration spike",
    description: "Discussed RGU-224 migration edge cases with Panshul — flagged URL alias handling",
    timestamp: `${TODAY}T11:20:00Z`,
    metadata: { channel: "#rgu-project", workspace: "Axelerant" },
    ticketKey: "RGU-224",
  },
  {
    id: "act-7",
    source: "jira",
    type: "ticket_update",
    title: "RGU-100 moved to Code Review",
    description: "Setup Subject Page content type — Panshul submitted for code review",
    timestamp: `${TODAY}T11:30:00Z`,
    metadata: { from: "In Progress", to: "Code Review", assignee: "Panshul Khurana" },
    ticketKey: "RGU-100",
  },
  {
    id: "act-8",
    source: "google_calendar",
    type: "meeting",
    title: "1:1 with Project Lead",
    description: "Weekly sync — discussed RGU sprint progress, AMS-495 bug priority, and L&D training reviews",
    timestamp: `${TODAY}T12:00:00Z`,
    metadata: { calendar: "Personal", attendees: "2" },
    durationMinutes: 30,
  },
  {
    id: "act-9",
    source: "github",
    type: "pr_review",
    title: "Reviewed PR: RGU-100 Subject Page content type",
    description: "Reviewed Panshul's Subject Page implementation — suggested field validation improvements",
    timestamp: `${TODAY}T13:00:00Z`,
    metadata: { repo: "axelerant/rgu-drupal", pr: "42", status: "approved" },
    ticketKey: "RGU-100",
  },
  {
    id: "act-10",
    source: "jira",
    type: "ticket_update",
    title: "RGU-178 updated — no estimate added",
    description: "Section Heading component — Sabreena is In Progress but no time estimate set",
    timestamp: `${TODAY}T13:15:00Z`,
    metadata: { action: "field_updated", assignee: "Sabreena Khursheed" },
    ticketKey: "RGU-178",
  },
  {
    id: "act-11",
    source: "github",
    type: "commit",
    title: "Add template and Twig for Landing Page",
    description: "Created Twig templates with layout builder integration for Landing Page content type",
    timestamp: `${TODAY}T14:00:00Z`,
    metadata: { repo: "axelerant/rgu-drupal", branch: "feature/RGU-97-landing-page", sha: "a2b9e71" },
    ticketKey: "RGU-97",
  },
  {
    id: "act-12",
    source: "github",
    type: "pr_opened",
    title: "PR #45: RGU-97 Landing Page content type",
    description: "Opens PR with full Landing Page content type — config, paragraphs, templates",
    timestamp: `${TODAY}T14:30:00Z`,
    metadata: { repo: "axelerant/rgu-drupal", pr: "45", reviewers: "Panshul, Sabreena" },
    ticketKey: "RGU-97",
  },
  {
    id: "act-13",
    source: "jira",
    type: "ticket_transition",
    title: "RGU-149 still in Code Review",
    description: "Header Right Pill component (50h estimate) — in Code Review for 5+ days, assigned to Sabreena",
    timestamp: `${TODAY}T14:45:00Z`,
    metadata: { status: "Code Review", assignee: "Sabreena Khursheed" },
    ticketKey: "RGU-149",
  },
  {
    id: "act-14",
    source: "google_calendar",
    type: "meeting",
    title: "RGU Architecture & Migration Review",
    description: "Reviewed migration strategy with team — discussed content type mapping and URL redirect plan",
    timestamp: `${TODAY}T15:30:00Z`,
    metadata: { calendar: "Engineering", attendees: "5" },
    durationMinutes: 60,
  },
  {
    id: "act-15",
    source: "jira",
    type: "ticket_update",
    title: "AMS-495 still in To Do (Urgent)",
    description: "BUG: Certificate + skill filter — Urgent priority, assigned to Roshni, no progress since Nov 2024",
    timestamp: `${TODAY}T16:00:00Z`,
    metadata: { status: "To Do", priority: "Urgent", assignee: "Roshni Upadhyay" },
    ticketKey: "AMS-495",
  },
  {
    id: "act-16",
    source: "slack",
    type: "message",
    title: "Asked about RGU-237 ownership in #rgu-project",
    description: "RGU-237 (Upcoming Events Block) is unassigned — asked team who can pick it up",
    timestamp: `${TODAY}T16:30:00Z`,
    metadata: { channel: "#rgu-project", workspace: "Axelerant" },
    ticketKey: "RGU-237",
  },
];

// ─── Timesheet Entries ──────────────────────────────────────────────────────

export const MOCK_TIMESHEET_ENTRIES: TimeEntry[] = [
  {
    id: "te-1",
    ticketKey: "RGU-97",
    ticketTitle: "Setup Landing Page content type",
    project: "Regent's University",
    description:
      "Built Landing Page content type — config YAML, paragraph types (hero, sections, CTA), Twig templates, opened PR #45",
    hours: 3.0,
    activities: ["act-3", "act-4", "act-5", "act-11", "act-12"],
    status: "draft",
    editedByUser: false,
  },
  {
    id: "te-2",
    ticketKey: "RGU-100",
    ticketTitle: "Setup Subject Page content type",
    project: "Regent's University",
    description:
      "Reviewed Panshul's PR for Subject Page content type — approved with field validation suggestions",
    hours: 0.75,
    activities: ["act-7", "act-9"],
    status: "draft",
    editedByUser: false,
  },
  {
    id: "te-3",
    ticketKey: "LDT-812",
    ticketTitle: "CSS Alternatives & Type Safety",
    project: "L&D Training",
    description:
      "Explored CSS-in-JS alternatives, documented type safety patterns for team training module",
    hours: 1.5,
    activities: [],
    status: "draft",
    editedByUser: false,
  },
  {
    id: "te-4",
    ticketKey: "AMS-495",
    ticketTitle: "BUG: Certificate + skill filter issue",
    project: "Axelerant/skillexai",
    description:
      "Investigated filter combination bug — identified root cause in query chain, needs fix implementation",
    hours: 0.5,
    activities: ["act-15"],
    status: "draft",
    editedByUser: false,
  },
  {
    id: "te-5",
    ticketKey: "",
    ticketTitle: "RGU Sprint Planning",
    project: "Meetings",
    description:
      "Sprint planning — backlog review, story pointing, and capacity planning for RGU sprint",
    hours: 0.75,
    activities: ["act-1", "act-2"],
    status: "draft",
    editedByUser: false,
  },
  {
    id: "te-6",
    ticketKey: "",
    ticketTitle: "1:1 & Architecture Review",
    project: "Meetings",
    description:
      "1:1 sync on sprint progress and priorities, followed by RGU migration architecture review with team",
    hours: 1.5,
    activities: ["act-8", "act-14"],
    status: "draft",
    editedByUser: false,
  },
];

// ─── Risk Alerts (Real data from Jira) ─────────────────────────────────────

export const MOCK_RISK_ALERTS: RiskAlert[] = [
  {
    id: "alert-1",
    severity: "critical",
    type: "stuck_ticket",
    title: "AMS-495 (Urgent) has no progress since Nov 2024",
    description:
      "This Urgent-priority bug has been in To Do since November 2024 with no activity. It affects certificate and skill filter combinations in skillexai. Assigned to Roshni Upadhyay but no work logged.",
    affectedTickets: ["AMS-495"],
    detectedAt: `${TODAY}T08:00:00Z`,
    suggestion:
      "AMS-495 is Urgent priority but has had no progress for 6+ months. Either begin implementation immediately, reassign to someone with bandwidth, or escalate to PM for re-prioritization.",
    suggestedAction: "Start implementation or reassign",
    isRead: false,
    isDismissed: false,
  },
  {
    id: "alert-2",
    severity: "high",
    type: "unassigned_critical",
    title: "RGU-237 (Upcoming Events Block) is unassigned",
    description:
      "This RGU ticket has no assignee and no time estimate. It's in Open status and blocks the events section of the Regent's University site.",
    affectedTickets: ["RGU-237"],
    detectedAt: `${TODAY}T08:00:00Z`,
    suggestion:
      "RGU-237 needs an owner. Based on current workload, consider assigning to Panshul (familiar with RGU component patterns) or Sabreena (available capacity after RGU-164 moves to Done).",
    suggestedAction: "Assign to Panshul",
    isRead: false,
    isDismissed: false,
  },
  {
    id: "alert-3",
    severity: "high",
    type: "stuck_ticket",
    title: "RGU-149 in Code Review for 5+ days (50h ticket)",
    description:
      "Header Right Pill component (50h estimate) has been in Code Review assigned to Sabreena for over 5 days with no reviewer activity. This is a large ticket that blocks the header navigation.",
    affectedTickets: ["RGU-149"],
    detectedAt: `${TODAY}T08:00:00Z`,
    suggestion:
      "RGU-149 is a 50h ticket stuck in Code Review. Assign a reviewer urgently — Roshni or Panshul can review. Consider breaking future large tickets into smaller reviewable chunks.",
    suggestedAction: "Assign reviewer",
    isRead: false,
    isDismissed: false,
  },
  {
    id: "alert-4",
    severity: "warning",
    type: "scope_creep",
    title: "RGU-178 has no time estimate (In Progress)",
    description:
      "Section Heading component is In Progress (Sabreena) but has no original time estimate. This makes sprint velocity tracking unreliable.",
    affectedTickets: ["RGU-178"],
    detectedAt: `${TODAY}T08:00:00Z`,
    suggestion:
      "Ask Sabreena to add a time estimate to RGU-178 before continuing. Without estimates, sprint burndown and capacity planning are inaccurate.",
    suggestedAction: "Add time estimate",
    isRead: false,
    isDismissed: false,
  },
  {
    id: "alert-5",
    severity: "warning",
    type: "unassigned_critical",
    title: "RGU-242 (Playwright testing) is unassigned",
    description:
      "Playwright automation testing integration ticket has no assignee. Test automation is critical for the RGU project quality gate.",
    affectedTickets: ["RGU-242"],
    detectedAt: `${TODAY}T08:00:00Z`,
    suggestion:
      "RGU-242 should be assigned to someone with Playwright experience. Consider assigning to Anjali (already doing test cases) or picking it up as a cross-team initiative.",
    suggestedAction: "Assign owner",
    isRead: false,
    isDismissed: false,
  },
];

// ─── Auto-Detected Pending Time Entries ─────────────────────────────────────

export const MOCK_PENDING_ENTRIES: PendingTimeEntry[] = [
  {
    id: "pte-1",
    source: "zoom",
    type: "zoom_call",
    title: "RGU Sprint Planning — Zoom Call",
    description: "Zoom meeting with 6 participants, 45 minutes",
    durationMinutes: 45,
    detectedAt: `${TODAY}T09:50:00Z`,
    project: "Meetings",
    metadata: { meetingId: "87654321", host: "pm@axelerant.com", participants: "6" },
    status: "pending",
  },
  {
    id: "pte-2",
    source: "zoom",
    type: "zoom_call",
    title: "1:1 with Project Lead — Zoom Call",
    description: "Zoom meeting with 2 participants, 30 minutes",
    durationMinutes: 30,
    detectedAt: `${TODAY}T12:35:00Z`,
    project: "Meetings",
    metadata: { meetingId: "87654322", host: "roshni.upadhyay@axelerant.com", participants: "2" },
    status: "pending",
  },
  {
    id: "pte-3",
    source: "slack",
    type: "slack_huddle",
    title: "Slack Huddle in #rgu-project",
    description: "Quick huddle with Panshul about migration edge cases for RGU-224",
    durationMinutes: 18,
    detectedAt: `${TODAY}T11:25:00Z`,
    ticketKey: "RGU-224",
    project: "Regent's University",
    metadata: { channel: "#rgu-project", participants: "2" },
    status: "pending",
  },
  {
    id: "pte-4",
    source: "jira",
    type: "ticket_time",
    title: "RGU-97 — Setup Landing Page content type",
    description: "In Progress for 3h 10m (09:50 → 13:00) based on Jira status transitions",
    durationMinutes: 190,
    detectedAt: `${TODAY}T13:00:00Z`,
    ticketKey: "RGU-97",
    project: "Regent's University",
    metadata: { startedAt: `${TODAY}T09:50:00Z`, status: "In Progress" },
    status: "pending",
  },
  {
    id: "pte-5",
    source: "jira",
    type: "ticket_time",
    title: "RGU-100 — Code Review for Subject Page",
    description: "Code Review for 45m — reviewed PR and provided feedback",
    durationMinutes: 45,
    detectedAt: `${TODAY}T13:45:00Z`,
    ticketKey: "RGU-100",
    project: "Regent's University",
    metadata: { startedAt: `${TODAY}T13:00:00Z`, status: "Code Review" },
    status: "pending",
  },
  {
    id: "pte-6",
    source: "zoom",
    type: "zoom_call",
    title: "RGU Architecture & Migration Review — Zoom Call",
    description: "Zoom meeting with 5 participants, 60 minutes",
    durationMinutes: 60,
    detectedAt: `${TODAY}T16:35:00Z`,
    project: "Meetings",
    metadata: { meetingId: "87654323", host: "pm@axelerant.com", participants: "5" },
    status: "pending",
  },
];

// ─── Dashboard Stats ────────────────────────────────────────────────────────

export const MOCK_STATS = {
  activitiesCaptured: MOCK_ACTIVITIES.length,
  hoursLogged: 0,
  activeAlerts: MOCK_RISK_ALERTS.filter((a) => !a.isDismissed).length,
  sprintProgress: 45,
  criticalAlerts: MOCK_RISK_ALERTS.filter((a) => a.severity === "critical").length,
  pendingEntries: 6,
};
