import type { Integration, Activity, TimeEntry, RiskAlert, PendingTimeEntry } from "./types";

// Today's date for demo purposes
const TODAY = "2026-04-29";

// ─── Integrations ───────────────────────────────────────────────────────────

export const MOCK_INTEGRATIONS: Integration[] = [
  {
    id: "int-1",
    source: "jira",
    displayName: "Jira",
    description: "Track tickets, sprint progress, and team velocity",
    connected: true,
    connectedAt: "2026-04-15T10:00:00Z",
    accountLabel: "axelerant.atlassian.net",
  },
  {
    id: "int-2",
    source: "github",
    displayName: "GitHub",
    description: "Monitor commits, pull requests, and code reviews",
    connected: true,
    connectedAt: "2026-04-15T10:05:00Z",
    accountLabel: "acme-corp",
  },
  {
    id: "int-3",
    source: "google_calendar",
    displayName: "Google Calendar",
    description: "Capture meetings, standups, and sprint ceremonies",
    connected: true,
    connectedAt: "2026-04-15T10:10:00Z",
    accountLabel: "roshni.upadhyay@axelerant.com",
  },
  {
    id: "int-4",
    source: "slack",
    displayName: "Slack",
    description: "Track project discussions and ticket-related threads",
    connected: true,
    connectedAt: "2026-04-15T10:15:00Z",
    accountLabel: "Axelerant",
  },
  {
    id: "int-5",
    source: "mavenlink",
    displayName: "Mavenlink",
    description: "Push approved timesheets and sync project hours",
    connected: false,
  },
  {
    id: "int-6",
    source: "granola",
    displayName: "Granola",
    description: "Import AI meeting notes and action items",
    connected: false,
  },
  {
    id: "int-7",
    source: "zoom",
    displayName: "Zoom",
    description: "Auto-detect call duration and log time from meetings",
    connected: true,
    connectedAt: "2026-04-15T10:20:00Z",
    accountLabel: "roshni.upadhyay@axelerant.com",
  },
];

// ─── Activities ─────────────────────────────────────────────────────────────

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: "act-1",
    source: "slack",
    type: "message",
    title: "Posted in #backend-team about sprint kickoff",
    description: "Shared agenda items and blockers for Sprint 14 planning",
    timestamp: `${TODAY}T08:32:00Z`,
    metadata: { channel: "#backend-team", workspace: "Acme Engineering" },
  },
  {
    id: "act-2",
    source: "google_calendar",
    type: "meeting",
    title: "Sprint 14 Planning",
    description: "Sprint planning session — capacity review, story pointing, and sprint goal alignment",
    timestamp: `${TODAY}T09:00:00Z`,
    metadata: { calendar: "Engineering", attendees: "8" },
    durationMinutes: 45,
  },
  {
    id: "act-3",
    source: "jira",
    type: "ticket_transition",
    title: "RGU-224 moved to In Progress",
    description: "Fix auth redirect loop — transitioned from To Do to In Progress",
    timestamp: `${TODAY}T09:52:00Z`,
    metadata: { from: "To Do", to: "In Progress", assignee: "You" },
    ticketKey: "RGU-224",
  },
  {
    id: "act-4",
    source: "github",
    type: "commit",
    title: "Fix token refresh race condition",
    description: "Resolved race condition where concurrent requests would invalidate each other's tokens",
    timestamp: `${TODAY}T10:15:00Z`,
    metadata: { repo: "acme-corp/backend-api", branch: "fix/auth-redirect", sha: "a3f7c21" },
    ticketKey: "RGU-224",
  },
  {
    id: "act-5",
    source: "github",
    type: "commit",
    title: "Add retry logic for expired sessions",
    description: "Added exponential backoff retry for session renewal on 401 responses",
    timestamp: `${TODAY}T10:48:00Z`,
    metadata: { repo: "acme-corp/backend-api", branch: "fix/auth-redirect", sha: "b8e4d15" },
    ticketKey: "RGU-224",
  },
  {
    id: "act-6",
    source: "github",
    type: "pr_opened",
    title: "PR #187: Fix auth redirect loop",
    description: "Opens PR with token refresh fix and retry logic for RGU-224",
    timestamp: `${TODAY}T11:05:00Z`,
    metadata: { repo: "acme-corp/backend-api", pr: "187", reviewers: "sarah, alex" },
    ticketKey: "RGU-224",
  },
  {
    id: "act-7",
    source: "slack",
    type: "message",
    title: "Requested review for PR #187 in #code-review",
    description: "Asked team to review the auth redirect fix, flagged as high priority",
    timestamp: `${TODAY}T11:30:00Z`,
    metadata: { channel: "#code-review", workspace: "Acme Engineering" },
    ticketKey: "RGU-224",
  },
  {
    id: "act-8",
    source: "google_calendar",
    type: "meeting",
    title: "1:1 with Sarah (EM)",
    description: "Weekly 1:1 — discussed Q3 migration timeline, career growth, and sprint priorities",
    timestamp: `${TODAY}T12:15:00Z`,
    metadata: { calendar: "Personal", attendees: "2" },
    durationMinutes: 30,
  },
  {
    id: "act-9",
    source: "github",
    type: "pr_review",
    title: "Reviewed PR #183: Dashboard query optimization",
    description: "Left feedback on query caching approach — suggested using Redis instead of in-memory cache",
    timestamp: `${TODAY}T13:30:00Z`,
    metadata: { repo: "acme-corp/frontend", pr: "183", status: "changes_requested" },
    ticketKey: "AMS-495",
  },
  {
    id: "act-10",
    source: "jira",
    type: "ticket_update",
    title: "LDT-812 updated — added subtask",
    description: "Added subtask: Wire up settings UI to preferences API",
    timestamp: `${TODAY}T14:00:00Z`,
    metadata: { subtask: "LDT-812-1", action: "subtask_added" },
    ticketKey: "LDT-812",
  },
  {
    id: "act-11",
    source: "github",
    type: "commit",
    title: "Add preference persistence layer",
    description: "Built PostgreSQL-backed persistence for user preferences with Prisma",
    timestamp: `${TODAY}T14:20:00Z`,
    metadata: { repo: "acme-corp/backend-api", branch: "feat/user-preferences", sha: "c9f2a38" },
    ticketKey: "LDT-812",
  },
  {
    id: "act-12",
    source: "github",
    type: "commit",
    title: "Wire up settings UI to preferences API",
    description: "Connected React settings form to new preferences endpoint with optimistic updates",
    timestamp: `${TODAY}T15:10:00Z`,
    metadata: { repo: "acme-corp/backend-api", branch: "feat/user-preferences", sha: "d1e3b47" },
    ticketKey: "LDT-812",
  },
  {
    id: "act-13",
    source: "jira",
    type: "ticket_transition",
    title: "LDT-812 moved to In Review",
    description: "User preferences API — transitioned from In Progress to In Review",
    timestamp: `${TODAY}T15:45:00Z`,
    metadata: { from: "In Progress", to: "In Review", assignee: "You" },
    ticketKey: "LDT-812",
  },
  {
    id: "act-14",
    source: "google_calendar",
    type: "meeting",
    title: "Backend Architecture Review",
    description: "Reviewed Q3 migration architecture — discussed database sharding strategy and API versioning",
    timestamp: `${TODAY}T16:00:00Z`,
    metadata: { calendar: "Engineering", attendees: "6" },
    durationMinutes: 60,
  },
  {
    id: "act-15",
    source: "github",
    type: "pr_opened",
    title: "PR #188: User preferences API",
    description: "Opens PR with preference persistence and settings UI integration for LDT-812",
    timestamp: `${TODAY}T17:10:00Z`,
    metadata: { repo: "acme-corp/backend-api", pr: "188", reviewers: "jordan, maya" },
    ticketKey: "LDT-812",
  },
];

// ─── Timesheet Entries ──────────────────────────────────────────────────────

export const MOCK_TIMESHEET_ENTRIES: TimeEntry[] = [
  {
    id: "te-1",
    ticketKey: "RGU-224",
    ticketTitle: "Spike - Migration (Address multiple scenarios)",
    project: "Regent's University",
    description:
      "Investigated migration scenarios, documented edge cases, opened spike analysis for review",
    hours: 2.5,
    activities: ["act-3", "act-4", "act-5", "act-6", "act-7"],
    status: "draft",
    editedByUser: false,
  },
  {
    id: "te-2",
    ticketKey: "LDT-812",
    ticketTitle: "CSS Alternatives & Type Safety",
    project: "L&D Training",
    description:
      "Explored CSS-in-JS alternatives, documented type safety patterns, prepared review notes",
    hours: 2.0,
    activities: ["act-10", "act-11", "act-12", "act-13", "act-15"],
    status: "draft",
    editedByUser: false,
  },
  {
    id: "te-3",
    ticketKey: "AMS-495",
    ticketTitle: "BUG: Certificate + skill filter issue",
    project: "Axelerant/skillexai",
    description:
      "Investigated filter combination bug, reviewed query logic, identified root cause in filter chain",
    hours: 0.5,
    activities: ["act-9"],
    status: "draft",
    editedByUser: false,
  },
  {
    id: "te-4",
    ticketKey: "",
    ticketTitle: "Sprint 14 Planning",
    project: "Meetings",
    description:
      "Sprint planning session — capacity review, story pointing, and sprint goal alignment with team",
    hours: 0.75,
    activities: ["act-1", "act-2"],
    status: "draft",
    editedByUser: false,
  },
  {
    id: "te-5",
    ticketKey: "",
    ticketTitle: "1:1 & Architecture Review",
    project: "Meetings",
    description:
      "1:1 with Sarah covering Q3 timeline and career growth, followed by backend architecture review for database sharding strategy",
    hours: 1.75,
    activities: ["act-8", "act-14"],
    status: "draft",
    editedByUser: false,
  },
];

// ─── Risk Alerts ────────────────────────────────────────────────────────────

export const MOCK_RISK_ALERTS: RiskAlert[] = [
  {
    id: "alert-1",
    severity: "critical",
    type: "stuck_ticket",
    title: "PROJ-98 blocked for 6 days",
    description:
      "This ticket has had no activity since April 23rd. The assigned engineer is also overloaded with 3 other in-progress items. The ticket is on the critical path for the Sprint 14 goal.",
    affectedTickets: ["PROJ-98"],
    detectedAt: `${TODAY}T08:00:00Z`,
    suggestion:
      "This ticket has had no activity since Apr 23. The assigned engineer is also overloaded with 3 other in-progress items. Consider reassigning to Maya (2 available capacity slots) or splitting the ticket into smaller, parallelizable tasks.",
    suggestedAction: "Reassign to Maya",
    isRead: false,
    isDismissed: false,
  },
  {
    id: "alert-2",
    severity: "high",
    type: "velocity_drop",
    title: "Sprint 14 velocity trending 30% below target",
    description:
      "3 of 8 planned stories haven't started yet. Two blockers (PROJ-98, PROJ-101) are causing cascading delays. At current pace, the team will complete only 5 of 8 planned stories.",
    affectedTickets: ["PROJ-98", "PROJ-101", "PROJ-112", "PROJ-115"],
    detectedAt: `${TODAY}T08:00:00Z`,
    suggestion:
      "3 of 8 planned stories haven't started. Two blockers (PROJ-98, PROJ-101) are causing cascading delays. Recommend a mid-sprint scope adjustment: move PROJ-112 and PROJ-115 to Sprint 15 to protect the sprint goal.",
    suggestedAction: "Adjust sprint scope",
    isRead: false,
    isDismissed: false,
  },
  {
    id: "alert-3",
    severity: "warning",
    type: "unassigned_critical",
    title: "PROJ-155 (P1 Bug) is unassigned",
    description:
      "A P1 bug was filed 2 days ago and still has no assignee. It affects the checkout flow and has been reported by 3 customers.",
    affectedTickets: ["PROJ-155"],
    detectedAt: `${TODAY}T08:00:00Z`,
    suggestion:
      "This P1 bug was filed 2 days ago and has no assignee. Based on domain expertise and current workload, recommend assigning to Alex (checkout flow expert, 1 capacity slot available) or Jordan (familiar with payments, 2 slots available).",
    suggestedAction: "Assign to Alex",
    isRead: false,
    isDismissed: false,
  },
];

// ─── Auto-Detected Pending Time Entries ─────────────────────────────────────

export const MOCK_PENDING_ENTRIES: PendingTimeEntry[] = [
  {
    id: "pte-1",
    source: "zoom",
    type: "zoom_call",
    title: "Sprint 14 Planning — Zoom Call",
    description: "Zoom meeting with 8 participants, 45 minutes",
    durationMinutes: 45,
    detectedAt: `${TODAY}T09:50:00Z`,
    project: "Meetings",
    metadata: { meetingId: "87654321", host: "sarah@acme-corp.com", participants: "8" },
    status: "pending",
  },
  {
    id: "pte-2",
    source: "zoom",
    type: "zoom_call",
    title: "1:1 with Sarah (EM) — Zoom Call",
    description: "Zoom meeting with 2 participants, 30 minutes",
    durationMinutes: 30,
    detectedAt: `${TODAY}T12:50:00Z`,
    project: "Meetings",
    metadata: { meetingId: "87654322", host: "you@acme-corp.com", participants: "2" },
    status: "pending",
  },
  {
    id: "pte-3",
    source: "slack",
    type: "slack_huddle",
    title: "Slack Huddle in #backend-team",
    description: "Quick huddle to debug auth token issue with Jordan",
    durationMinutes: 22,
    detectedAt: `${TODAY}T11:00:00Z`,
    ticketKey: "RGU-224",
    project: "Backend API",
    metadata: { channel: "#backend-team", participants: "3" },
    status: "pending",
  },
  {
    id: "pte-4",
    source: "jira",
    type: "ticket_time",
    title: "RGU-224 — Spike - Migration (Address multiple scenarios)",
    description: "In Progress for 2h 35m (09:52 → 12:27) based on Jira status transitions",
    durationMinutes: 155,
    detectedAt: `${TODAY}T12:27:00Z`,
    ticketKey: "RGU-224",
    project: "Regent's University",
    metadata: { startedAt: `${TODAY}T09:52:00Z`, status: "In Progress" },
    status: "pending",
  },
  {
    id: "pte-5",
    source: "jira",
    type: "ticket_time",
    title: "LDT-812 — CSS Alternatives & Type Safety",
    description: "In Review for 1h 45m (14:00 → 15:45) based on Jira status transitions",
    durationMinutes: 105,
    detectedAt: `${TODAY}T15:45:00Z`,
    ticketKey: "LDT-812",
    project: "L&D Training",
    metadata: { startedAt: `${TODAY}T14:00:00Z`, status: "In Review" },
    status: "pending",
  },
  {
    id: "pte-6",
    source: "zoom",
    type: "zoom_call",
    title: "Backend Architecture Review — Zoom Call",
    description: "Zoom meeting with 6 participants, 60 minutes",
    durationMinutes: 60,
    detectedAt: `${TODAY}T17:05:00Z`,
    project: "Meetings",
    metadata: { meetingId: "87654323", host: "sarah@acme-corp.com", participants: "6" },
    status: "pending",
  },
];

// ─── Dashboard Stats ────────────────────────────────────────────────────────

export const MOCK_STATS = {
  activitiesCaptured: MOCK_ACTIVITIES.length,
  hoursLogged: 0,
  activeAlerts: MOCK_RISK_ALERTS.filter((a) => !a.isDismissed).length,
  sprintProgress: 64,
  criticalAlerts: MOCK_RISK_ALERTS.filter((a) => a.severity === "critical").length,
  pendingEntries: 6,
};
